### ISSUE TITLE
Return from iframe

### ISSUE THREAD

**Issue by tuvokki** [SergeyRolich/ionic2-keycloak#1]
Hi,

fantastic work on the ionic-keycloak integration, it really helped me a lot in understanding how the process works. I have a question about the iframe (?) that opens when the app goes to the login (or signup) flow, it shows a 'Done'-button and some navigation arrows in the bottom.

![img_0064](https://user-images.githubusercontent.com/181719/28238362-59074326-6952-11e7-9ed9-4cb37299a159.jpg)

After successfully logging in I get redirected to a website (I'ts a shared keycloak with a webapplication so the redirect might be due to a wrong configuration on the keycloak-redirect site) and the done and navigation buttons remain.

![img_0065](https://user-images.githubusercontent.com/181719/28238408-1611f344-6953-11e7-85e9-a12feb9f6ed7.jpg)
(never mind the 'Fatal error', this is expected behaviour, we're absolutely logged-in)

For my flow I'd like to return to the ionic app after logging in, and use the session I created during the login flow.

1. is this an iframe, or some kind of webview?
2. how do I close this to return to the app when I'm on a device?

Hope you can shed some light on this.

Kind regards,
Wouter

**Comment by SergeyRolich** [comment]
Hi. 
Why do you use iframe? Is it possible to do without it?

**Comment by tuvokki** [comment]
When running on a device I can see in the debugger that it is using the `cordova-plugin-inappbrowser` plugin, which answers my first question. Yet the redirect takes place and my app remains in the inappbrowser window.
