### ISSUE TITLE
testable in browser?

### ISSUE THREAD

**Issue by seiyria** [SergeyRolich/ionic2-keycloak#2]
Is this testable in the browser? I'm having a few issues implementing this as-is and I'm fairly new to keycloak so I'm not sure what's up.

Right now, whenever I do a login, the page refreshes after putting a state in the URL, for example.

Thanks!

**Comment by seiyria** [comment]
Nevermind. Turns out I was somehow authenticated, probably from a prior session or somewhere else. Calling login while authenticated forces a page refresh, which, while undesirable, is not a problem if it never happens. Thanks for the great example!

**Comment by SergeyRolich** [comment]
You are welcome!
